<?php
/**
 * Created by PhpStorm.
 * User: xiejun
 * Date: 2018/1/8
 * Time: 下午3:47
 */
$log='ACBDEGIIJKM ABCIEGIHDJKM ACBDEGGIJKM ACKDEGIHIJBM AGBDFCIJKM ABCDEGIHIJKM ABCDFGIJKM ACBDFGIJKM ABCDEGIHIJKM ACBDFGIHIJKM ABCDFGIHIJKM ACBDEGIJKM ABCDFGIJKM ACBDFGIHIJKM ACBDEGIHIJKM ACBDEGIJKM ABCDEGIHIJKM ACBDFGIJKM ACBDFGIHIJKM ABCDEGIHIJKM ABCDFGIJKM ACBDFGIHIJKM ACBDEGIHIJKM ABCDEGIHIJKM ABCDEGIJKM ABCDEGIJKM ACBDFGIJKM ABCDEGIJKM ABCDFGIHIJKM ACBDEGIJKM ACBDEGIJKM ACBDFGIHIJKM ACBDFGIHIJKM ACBDFGIJKM ACBDEGIHIJKM ABCDEGIJKM ACBDFGIJKM ABCDEGIHIJKM ACBDEGIHIJKM ABCDEGIJKM ACBDEGIHIJKM ACBDEGIHIJKM ABCDFGIHIJKM ACBDEGIHIJKM ACBDFGIHIJKM ACBDEGIJKM ACBDFGIJKM ACBDFGIJKM ABCDEGIJKM ACBDEGIJKM ACBDEGIHIJKM ACBDFGIHIJKM ABCDEGIJKM ACBDEGIJKM ACBDFGIHIJKM ACBDFGIHIJKM ACBDEGIJKM ACBDEGIJKM ABCDFGIJKM ACBDEGIHIJKM ACBDEGIJKM ACBDFGIJKM ACBDEGIJKM ABCDFGIJKM ABCDFGIHIJKM ACBDEGIHIJKM ABCDFGIHIJKM ABCDEGIHIJKM ACBDEGIHIJKM ABCDFGIJKM ACBDFGIHIJKM ACBDEGIHIJKM ACBDFGIJKM ABCDFGIHIJKM ACBDFGIHIJKM ABCDFGIHIJKM ACBDEGIJKM ACBDEGIHIJKM ACBDEGIHIJKM ABCDEGIHIJKM ACBDFGIHIJKM ACBDFGIJKM ACBDFGIHIJKM ACBDEGIJKM ABCDEGIJKM ACBDEGIHIJKM ACBDEGIHIJKM ACBDEGIJKM ABCDFGIJKM ABCDEGIJKM ACBDFGIJKM ACBDEGIHIJKM ABCDEGIHIJKM ACBDFGIHIJKM ACBDEGIJKM ABCDEGIJKM ABCDEGIHIJKM ABCDEGIJKM ABCDFGIHIJKM ACBDFGIHIJKM';

$traces=[];
$count=[];
$buf=explode(' ',$log);
//print_r(count($buf));
for ($i=0;$i<count($buf);$i++){
    if (in_array($buf[$i],$traces)){
        $key=array_search($buf[$i],$traces);
        $count[$key]++;
    }else{
        array_push($traces,$buf[$i]);
        array_push($count,1);
    }
}

//print_r($traces);
//print_r($count);
//foreach ($traces as $v){
//    echo "'".$v."'".',';
//}
foreach ($count as $v){
    echo $v.',';
}
