<?php
/**
 * Created by PhpStorm.
 * User: xiejun
 * Date: 2017/12/26
 * Time: 上午10:58
 */
$log='ACBDEJIGKM ABCDDEGIHIJKM ACBGEDIJKM ABDEGIHIJKM ABCCDFGIHIJKM ABCDFGIHIKM ACBDEGIHHIJKM ABCDEGIJJKM ACBDFGJKM ACBDFGGIHIJKM ABCDFGMJKI ABCDFGJKM JBCDFGIAKM ACCBDEGIHIJKM ABCDEGIIHIJKM ABBCDEGIHIJKM ABCDFGMHIJKI ACGDFBIJKM ABCDFGJKM ABCIEGDHIJKM ACBDFGIJKM ACBDEGIHIJKM ABCDFGIHIJKM ACBDFGIHIJKM ABCDFGIHIJKM ABCDFGIHIJKM ABCDFGIHIJKM ABCDFGIHIJKM ACBDFGIJKM ACBDEGIHIJKM ABCDFGIJKM ACBDFGIHIJKM ACBDFGIHIJKM ACBDFGIJKM ABCDEGIJKM ACBDEGIJKM ABCDFGIJKM ACBDEGIHIJKM ABCDEGIJKM ABCDFGIJKM ABCDEGIHIJKM ABCDFGIJKM ACBDEGIHIJKM ABCDEGIJKM ABCDFGIJKM ACBDEGIHIJKM ABCDFGIHIJKM ABCDFGIJKM ACBDFGIHIJKM ABCDFGIHIJKM ABCDEGIJKM ACBDFGIHIJKM ACBDEGIJKM ABCDEGIHIJKM ABCDEGIJKM ACBDEGIJKM ABCDFGIJKM ABCDEGIHIJKM ABCDFGIHIJKM ACBDEGIHIJKM ABCDFGIJKM ACBDEGIJKM ACBDEGIHIJKM ACBDEGIHIJKM ACBDFGIHIJKM ACBDFGIJKM ABCDFGIHIJKM ACBDFGIHIJKM ABCDEGIJKM ABCDEGIHIJKM ABCDFGIHIJKM ACBDEGIHIJKM ACBDFGIHIJKM ABCDEGIHIJKM ABCDFGIJKM ABCDEGIHIJKM ACBDFGIJKM ABCDFGIJKM ABCDFGIJKM ABCDEGIJKM ABCDEGIHIJKM ACBDFGIJKM ABCDEGIHIJKM ACBDFGIHIJKM ABCDEGIHIJKM ACBDEGIHIJKM ACBDFGIHIJKM ABCDFGIHIJKM ABCDEGIHIJKM ABCDEGIHIJKM ACBDFGIHIJKM ACBDEGIJKM ACBDEGIHIJKM ABCDEGIHIJKM ABCDFGIHIJKM ACBDFGIJKM ACBDEGIJKM ACBDEGIJKM ACBDEGIHIJKM ABCDFGIHIJKM';
$str='';
$count=0;

$buf=explode(' ',$log);
for ($i=0;$i<count($buf);$i++){
    $count++;
    $arr=str_split($buf[$i]);
    for ($j=0;$j<count($arr);$j++){
        $str.=$count.';'.$arr[$j]."\n";
    }
}


$fp2=fopen('fileCSV.txt','w');
fwrite($fp2,$str);
fclose($fp2);