<?php
/**
 * Created by PhpStorm.
 * User: xiejun
 * Date: 2018/1/8
 * Time: 下午3:47
 */
$log='ABDCEGIJKM ABCDEGMJKI ACBDFGIHIJKM ABCDEGIJKM ACBDEGIHIJKM ABCDEGIJKM ABCDEGIHIJKM ACBDEGIHIJKM ACBDFGIJKM ACBDFGIJKM ABCDEGIHIJKM ACBDFGIJKM ACBDFGIHIJKM ACBDEGIHIJKM ABCDFGIJKM ABCDEGIJKM ABCDFGIHIJKM ABCDFGIHIJKM ABCDEGIJKM ACBDEGIJKM ABCDEGIHIJKM ABCDFGIHIJKM ABCDEGIJKM ACBDFGIHIJKM ABCDFGIJKM ACBDFGIJKM ACBDFGIHIJKM ACBDEGIHIJKM ABCDEGIHIJKM ACBDFGIJKM ACBDFGIJKM ACBDFGIHIJKM ACBDFGIJKM ACBDEGIHIJKM ACBDFGIHIJKM ABCDFGIJKM ACBDEGIJKM ABCDFGIJKM ACBDEGIHIJKM ABCDEGIHIJKM ACBDFGIJKM ABCDEGIJKM ABCDFGIJKM ABCDFGIJKM ABCDEGIHIJKM ABCDEGIHIJKM ABCDEGIJKM ACBDFGIJKM ACBDFGIHIJKM ABCDEGIJKM ACBDEGIJKM ABCDFGIJKM ACBDFGIJKM ACBDFGIJKM ACBDFGIJKM ABCDFGIHIJKM ABCDEGIJKM ACBDEGIHIJKM ACBDFGIJKM ABCDFGIJKM ACBDFGIHIJKM ABCDEGIJKM ABCDFGIHIJKM ACBDEGIHIJKM ABCDEGIJKM ACBDEGIHIJKM ABCDFGIJKM ABCDFGIHIJKM ACBDEGIHIJKM ACBDEGIJKM ACBDFGIHIJKM ACBDFGIHIJKM ACBDEGIJKM ABCDFGIHIJKM ABCDEGIHIJKM ABCDEGIJKM ACBDFGIHIJKM ACBDEGIJKM ABCDEGIHIJKM ACBDFGIHIJKM ABCDEGIHIJKM ABCDFGIJKM ABCDEGIHIJKM ACBDFGIHIJKM ABCDFGIHIJKM ACBDEGIJKM ABCDFGIHIJKM ACBDFGIHIJKM ABCDFGIHIJKM ACBDEGIJKM ACBDEGIHIJKM ACBDFGIHIJKM ABCDEGIHIJKM ABCDEGIJKM ACBDEGIHIJKM ACBDEGIHIJKM ACBDEGIHIJKM ACBDEGIHIJKM ABCDEGIHIJKM ACBDEGIHIJKM';

$traces=[];
$count=[];
$buf=explode(' ',$log);
//print_r(count($buf));
for ($i=0;$i<count($buf);$i++){
    if (in_array($buf[$i],$traces)){
        $key=array_search($buf[$i],$traces);
        $count[$key]++;
    }else{
        array_push($traces,$buf[$i]);
        array_push($count,1);
    }
}

//print_r($traces);
//print_r($count);

//foreach ($traces as $v){
//    echo "'".$v."'".',';
//}
foreach ($count as $v){
    echo $v.',';
}
