<?php
/**
 * Created by PhpStorm.
 * User: xiejun
 * Date: 2017/12/26
 * Time: 上午10:58
 */
$log='ACCBDEGIHIJKM ACBDDEGIJKM ACBDFGIJKMM ABCDFGIHIJJKM ACBDDEGIHIJKM ACBDEGIIJKM ABDFGIHIJKM ABCCDEGIJKM ABCFGIJKM ABCDFGIHIJKM ACBDEGIHIJKM ACBDFGIJKM ABCDEGIJKM ABCDFGIHIJKM ACBDEGIHIJKM ABCDFGIJKM ACBDFGIJKM ABCDFGIHIJKM ACBDEGIJKM ABCDFGIJKM ACBDEGIJKM ABCDEGIJKM ACBDFGIJKM ABCDFGIHIJKM ACBDFGIJKM ACBDEGIJKM ACBDFGIJKM ACBDFGIHIJKM ABCDFGIJKM ABCDFGIJKM ACBDEGIJKM ACBDFGIJKM ACBDFGIJKM ABCDFGIHIJKM ABCDFGIHIJKM ACBDEGIHIJKM ABCDFGIJKM ABCDFGIHIJKM ACBDFGIHIJKM ABCDFGIJKM ACBDEGIJKM ABCDFGIJKM ACBDFGIJKM ACBDFGIJKM ABCDEGIHIJKM ACBDFGIJKM ACBDEGIJKM ACBDFGIJKM ABCDFGIHIJKM ABCDFGIHIJKM ABCDEGIHIJKM ACBDEGIJKM ACBDEGIJKM ABCDFGIHIJKM ACBDEGIHIJKM ABCDFGIHIJKM ACBDFGIJKM ACBDEGIHIJKM ABCDFGIJKM ACBDFGIHIJKM ABCDFGIHIJKM ACBDFGIHIJKM ACBDFGIJKM ABCDEGIJKM ACBDFGIJKM ABCDEGIHIJKM ACBDEGIJKM ACBDFGIHIJKM ACBDFGIJKM ABCDEGIJKM ABCDEGIHIJKM ABCDEGIHIJKM ABCDEGIJKM ACBDEGIJKM ABCDFGIJKM ABCDEGIJKM ABCDFGIHIJKM ABCDFGIJKM ACBDEGIHIJKM ABCDEGIJKM ACBDEGIJKM ABCDEGIHIJKM ACBDFGIJKM ABCDEGIHIJKM ABCDEGIJKM ACBDFGIHIJKM ACBDEGIHIJKM ACBDEGIHIJKM ABCDFGIHIJKM ABCDEGIJKM ABCDFGIJKM ACBDFGIHIJKM ACBDFGIJKM ACBDEGIJKM ABCDFGIJKM ABCDFGIJKM ABCDEGIJKM ABCDEGIHIJKM ABCDFGIHIJKM ACBDFGIHIJKM';
$str='';
$count=0;

$buf=explode(' ',$log);
for ($i=0;$i<count($buf);$i++){
    $count++;
    $arr=str_split($buf[$i]);
    for ($j=0;$j<count($arr);$j++){
        $str.=$count.';'.$arr[$j]."\n";
    }
}


$fp2=fopen('fileCSV.txt','w');
fwrite($fp2,$str);
fclose($fp2);